project:
  type: website

website:
  favicon: logo.png
  title: "Asa Rogers"
  navbar:
    logo: logo.png
    title: false
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: writing.qmd
        text: Writing
      - href: projects.qmd
        text: Projects
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/awroger22
      - icon: linkedin
        href: www.linkedin.com/in/asa-rogers
  page-footer: "© 2026 Asa Rogers"

format:
  html:
    theme: darkly
    css: styles.css